### ISSUE TITLE
Feat: 사이트 개편

### ISSUE THREAD

**Issue by sjsjsj1246** [EndlessCreation/EC_Community_Front#62]
## Description

사용하지 않는 사이트 기능들과 화면은 제거하고 최소한으로 남겨둡니다.

## Todo

- [ ] configure typscript, babel
- [ ] store 재설정
- [ ] community, admin 관련 화면 제거
- [ ] 기존 애니메이션 관련 로직 제거
- [ ] 불필요한 의존성 제거
- [ ] 1학기 모집 관련 내용 제거

## References

없음
