### ISSUE TITLE
Feat: 2023 사이트 개편

### ISSUE THREAD

**Issue by sjsjsj1246** [EndlessCreation/EC_Community_Front#64]
## Todo

- [x] 2023 활동과 모집 게획과 관련된 내용수정
- [x] 필요없는 라이브러리, 코드 제거
- [x] 기존 코드 리펙토링
- [x] CI / CD 환경 구축
